export enum textTypes {
  TITLE_REGULAR = 'TITLE_REGULAR', // 24px
  SUB_TITLE_REGULAR = 'SUB_TITLE_REGULAR', // 20px
  PARAGRAPH_REGULAR = 'PARAGRAPH_REGULAR', // 14px
  PARAGRAPH_SMALL_REGULAR = 'PARAGRAPH_SMALL_REGULAR', // 10px
  BUTTON_REGULAR = 'BUTTON_REGULAR', // 18px
}
